name: ams-env
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.14=openblas
  - ca-certificates
  - certifi
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - cytoolz=0.9.0.1
  - dill=0.2.9
  - idna=2.8
  - msgpack-numpy=0.4.3.2
  - msgpack-python=0.6.2
  - murmurhash=1.0.0
  - ncurses=6.1
  - pip=19.3.1
  - plac=0.9.6
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.1
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.6.0
  - six=1.13.0
  - spacy-lookups-data=0.2.0
  - sqlite=3.30.1
  - toolz=0.10.0
  - tqdm=4.38.0
  - urllib3=1.25.7
  - wheel=0.33.6
  - wrapt=1.10.11
  - xz=5.2.4
  - pip:
    - appnope==0.1.0
    - astunparse==1.6.2
    - attrs==19.3.0
    - awscli==1.16.298
    - backcall==0.1.0
    - beautifulsoup4==4.8.1
    - bleach==3.1.0
    - blis==0.4.1
    - boto3==1.10.34
    - botocore==1.13.34
    - catalogue==0.0.8
    - click==7.0
    - colorama==0.4.1
    - conllu==2.2
    - cycler==0.10.0
    - deap==1.3.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - docutils==0.15.2
    - entrypoints==0.3
    - ftfy==5.6
    - gensim==3.8.1
    - importlib-metadata==1.1.0
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - mlxtend==0.17.1
    - more-itertools==8.0.0
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - nmslib==2.0.5
    - notebook==6.0.2
    - numpy==1.17.4
    - pandas==0.25.3
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pmlb==0.3
    - preshed==3.0.2
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - psutil==5.6.7
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pybind11==2.4.3
    - pygments==2.4.2
    - pyparsing==2.4.5
    - pyrsistent==0.15.6
    - pysbd==0.2.3
    - python-dateutil==2.8.0
    - pytz==2019.3
    - pyyaml==5.1.2
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - rsa==3.4.2
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - scikit-learn==0.21.3
    - scipy==1.3.2
    - scispacy==0.2.4
    - seaborn==0.10.0
    - send2trash==1.5.0
    - sentencepiece==0.1.83
    - soupsieve==1.9.5
    - spacy==2.2.3
    - spacy-transformers==0.5.1
    - srsly==0.2.0
    - stopit==1.1.2
    - terminado==0.8.3
    - testpath==0.4.4
    - thinc==7.3.1
    - torch==1.3.1
    - torchcontrib==0.0.2
    - tornado==6.0.3
    - traitlets==4.3.3
    - transformers==2.0.0
    - update-checker==0.16
    - wasabi==0.4.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - xgboost==1.0.1
    - zipp==0.6.0
    - zss==1.2.0
